scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          env: local
          region: eu-west-1

  - job_name: 'helloworld_gunicorn'
    scrape_interval: 5s
    static_configs:
      - targets: ['statsd:9102']
